const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const CREATE_PRODUCT = 'CREATE_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const ERROR = 'ERROR';
const RESET_CART = "RESET_CART";
const FETCH_PRODUCT = 'FETCH_PRODUCT';
const ADD_REVIEW = 'ADD_REVIEW';
const REMOVE_REVIEW = 'REMOVE_REVIEW';
const CREATE_ORDER = 'CREATE_ORDER';
const FETCH_ORDERS = 'FETCH_ORDERS';
const ADD_SHIPPING = 'ADD_SHIPPING';

export { 
  ADD_TO_CART,
  REMOVE_FROM_CART, 
  FETCH_PRODUCTS, 
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  REMOVE_PRODUCT,
  ERROR, 
  RESET_CART,
  FETCH_PRODUCT,
  ADD_REVIEW,
  REMOVE_REVIEW,
  CREATE_ORDER,
  FETCH_ORDERS,
  ADD_SHIPPING,
}