const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const ERROR = "ERROR";
const RESET_CART = "RESET_CART";

export { ADD_TO_CART, REMOVE_FROM_CART, FETCH_PRODUCTS, ERROR}