const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const CREATE_PRODUCT = 'CREATE_PRODUCT';
const ERROR = 'ERROR';
const RESET_CART = "RESET_CART";
const FETCH_PRODUCT = 'FETCH_PRODUCT';
const ADD_REVIEW = 'ADD_REVIEW';
const REMOVE_REVIEW = 'REMOVE_REVIEW';




export { 
  ADD_TO_CART,
  REMOVE_FROM_CART, 
  FETCH_PRODUCTS, 
  CREATE_PRODUCT,
  ERROR, 
  RESET_CART,
  FETCH_PRODUCT,
  ADD_REVIEW,
  REMOVE_REVIEW
}